/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#68000c",
        "error-container": "#93000a",
        "surface-dim": "#131411",
        "surface-bright": "#3a3936",
        "on-primary-container": "#5c0009",
        "surface": "#131411",
        "on-primary-fixed-variant": "#900a18",
        "surface-container": "#20201d",
        "outline-variant": "#59413f",
        "on-surface-variant": "#e1bebc",
        "tertiary-container": "#c98100",
        "on-primary-fixed": "#410004",
        "on-surface": "#e5e2dd",
        "surface-container-low": "#1c1c19",
        "secondary": "#a4c9ff",
        "surface-variant": "#353532",
        "inverse-on-surface": "#31302d",
        "on-tertiary": "#462a00",
        "surface-container-high": "#2a2a27",
        "secondary-fixed": "#d4e3ff",
        "primary": "#ffb3ae",
        "background": "#131411",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-tint": "#ffb3ae",
        "surface-container-highest": "#353532",
        "tertiary": "#ffb95d",
        "on-error": "#690005",
        "on-tertiary-fixed": "#2a1700",
        "inverse-primary": "#b3282c",
        "tertiary-fixed": "#ffddb7",
        "on-background": "#e5e2dd",
        "inverse-surface": "#e5e2dd",
        "on-tertiary-container": "#3d2400",
        "on-secondary": "#00315d",
        "surface-container-lowest": "#0e0e0c",
        "secondary-fixed-dim": "#a4c9ff",
        "on-secondary-container": "#a3c8ff",
        "on-secondary-fixed": "#001c39",
        "outline": "#a98987",
        "primary-container": "#f85b58",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#ffb3ae",
        "tertiary-fixed-dim": "#ffb95d",
        "secondary-container": "#005398",
        "primary-fixed": "#ffdad7",
        "on-secondary-fixed-variant": "#004883",
        "on-error-container": "#ffdad6",
        "game-red": "#E24B4A",
        "game-blue": "#185FA5",
        "game-cell": "#1A1A1A",
        "game-border": "#2A2A2A"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "16px",
        "xs": "4px",
        "grid-gap": "12px",
        "unit": "4px",
        "sm": "8px",
        "lg": "24px",
        "xl": "40px",
        "container-padding": "24px"
      },
      fontFamily: {
        "display-xl": ["Syncopate", "sans-serif"],
        "display-lg": ["Syncopate", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "label-caps": ["Outfit", "sans-serif"],
        "body-lg": ["Outfit", "sans-serif"],
        "body-sm": ["Outfit", "sans-serif"]
      },
      fontSize: {
        "display-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "display-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "1.4", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
